# Generated by Django 6.0.6 on 2026-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='管理员拒绝注册时填写的理由，用户登录时可查看', verbose_name='拒绝原因'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('active', '正常'), ('rejected', '已拒绝'), ('banned', '已封禁')], default='active', help_text='pending=待审核 active=正常 rejected=已拒绝 banned=已封禁', max_length=20, verbose_name='账号状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id_card',
            field=models.ImageField(blank=True, help_text='注册时上传的学生证照片，用于身份验证', null=True, upload_to='student_id_cards/%Y/%m/', verbose_name='学生证照片'),
        ),
    ]
