# Generated by Django 6.0.6 on 2026-06-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_rejection_reason_user_status_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE users SET status = 'banned' WHERE is_active = 0;",
            reverse_sql="UPDATE users SET status = 'active' WHERE status = 'banned';",
        ),
    ]
