# Generated by Django 5.1.15 on 2026-06-04 02:36

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceConfirm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('confirm_code', models.CharField(max_length=6, verbose_name='确认码')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('expired', '已过期')], default='pending', max_length=10, verbose_name='确认状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
            ],
            options={
                'verbose_name': '面交确认',
                'verbose_name_plural': '面交确认',
                'db_table': 'face_confirms',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('pending', '等待卖家确认'), ('accepted', '已接受，待面交'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('face_confirm', '面交确认中'), ('completed', '已完成')], db_index=True, default='pending', max_length=20, verbose_name='订单状态')),
                ('meet_time', models.DateTimeField(blank=True, null=True, verbose_name='约定面交时间')),
                ('meet_location', models.CharField(blank=True, max_length=200, verbose_name='面交地点')),
                ('cancel_reason', models.CharField(blank=True, max_length=500, verbose_name='取消原因')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('buyer_rated', models.BooleanField(default=False, verbose_name='买家已评价')),
                ('seller_rated', models.BooleanField(default=False, verbose_name='卖家已评价')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='评价内容')),
                ('review_type', models.CharField(choices=[('buyer_to_seller', '买家评价卖家'), ('seller_to_buyer', '卖家评价买家')], max_length=20, verbose_name='评价类型')),
            ],
            options={
                'verbose_name': '交易评价',
                'verbose_name_plural': '交易评价',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
