# Generated by Django 5.1.15 on 2026-06-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_review_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="order",
            name="buyer_rated",
        ),
        migrations.RemoveField(
            model_name="order",
            name="seller_rated",
        ),
        migrations.AddField(
            model_name="order",
            name="buyer_review_count",
            field=models.IntegerField(default=0, verbose_name="买家评价次数"),
        ),
        migrations.AddField(
            model_name="order",
            name="seller_review_count",
            field=models.IntegerField(default=0, verbose_name="卖家评价次数"),
        ),
    ]
