# Generated by Django 5.1.15 on 2026-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_report_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("active", "在售"),
                    ("reserved", "已预定"),
                    ("sold", "已售出"),
                    ("hidden", "已隐藏"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="商品状态",
            ),
        ),
    ]
