# Generated by Django 5.1.15 on 2026-06-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_status_add_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("active", "在售"),
                    ("reserved", "已预定"),
                    ("sold", "已售出"),
                    ("hidden", "已隐藏"),
                    ("banned", "违规下架"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="商品状态",
            ),
        ),
    ]
