# Generated by Django 5.1.15 on 2026-06-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_banned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reject_reason',
            field=models.CharField(blank=True, help_text='审核驳回时填写的原因', max_length=300, verbose_name='驳回原因'),
        ),
    ]
