# Generated by Django 5.1.15 on 2026-06-15 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_reject_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(max_length=1000, verbose_name='评论内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment_images/%Y/%m/', verbose_name='评论图片')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('parent', models.ForeignKey(blank=True, help_text='为空表示一级评论，有值表示回复', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products.comment', verbose_name='回复对象')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
                'db_table': 'comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='comments_product_981ca6_idx'), models.Index(fields=['parent', '-created_at'], name='comments_parent__b79743_idx')],
            },
        ),
    ]
